/* ============================================================
   Summit SAT — video learning links
   ------------------------------------------------------------
   Two kinds of link, deliberately:

   1. SEARCH LINKS (always present). A precise YouTube search
      phrase per skill. These can never 404 or go stale — the
      results page always reflects whatever is currently best.
   2. PICKS (optional). Specific videos, only ever added here
      after being found in real search results and independently
      corroborated. Never write one from memory; a wrong video ID
      sends a student to a dead or unrelated page.

   Every skill works with search links alone, so picks are purely
   a bonus and the feature degrades gracefully without them.

   This file is generated by tools/integrate-videos.js.
   ============================================================ */

function ytSearchUrl(query) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(query);
}

/* Trusted channels, shown as general "where to learn this" links.
   Populated only with independently corroborated entries. */
const VIDEO_CHANNELS = [
  { name: "Khan Academy", url: "https://www.youtube.com/@khanacademy", why: "Official College Board partner; free Digital SAT Reading & Writing lessons and worked examples aligned to the " },
  { name: "PrepPros - SAT & ACT Test Prep", url: "https://www.youtube.com/@preppros", why: "Professional tutor channel with step-by-step Reading & Writing question walkthroughs and strategy guides, free" },
  { name: "Penguin SAT Prep", url: "https://www.youtube.com/@PenguinTestPrep", why: "Tutor-run channel covering Reading & Writing in depth by question type, useful for drilling one Information an" },
  { name: "Hayden Rhodea SAT", url: "https://www.youtube.com/@haydenrhodea761", why: "Recent high-scoring test-taker; peer-level walkthroughs and section strategies for Digital SAT Reading & Writi" },
  { name: "SAT Mastermind", url: "https://www.youtube.com/@SATMastermind", why: "Focused specifically on raising the Reading & Writing score; question-type strategy videos for the digital for" },
  { name: "SupertutorTV", url: "https://www.youtube.com/@SupertutorTV", why: "Brooke Hanson (perfect SAT scorer) does clear strategy breakdowns and hard-question walkthroughs specifically " },
  { name: "Ivy League Mentors", url: "https://www.youtube.com/@ivyleaguementors", why: "Digital-SAT-specific question-type breakdowns; has dedicated Transitions and Rhetorical Synthesis strategy vid" },
  { name: "The Test Advantage with Mr. Osama A. Ibrahim", url: "https://www.youtube.com/@TheTestAdvantage", why: "Active Digital-SAT-only channel posting short-form and full walkthroughs of current question styles, including" },
  { name: "Khan Academy SAT", url: "https://www.youtube.com/@KhanAcademyNewSAT", why: "Official College Board partner; free, fully aligned Digital SAT Reading & Writing grammar lessons and worked e" },
  { name: "Tutorllini Test Prep", url: "https://www.youtube.com/@Tutorllini", why: "Works through official College Board Digital SAT questions step by step, including full question-bank playlist" },
  { name: "Scalar Learning", url: "https://www.youtube.com/@ScalarLearning", why: "Detailed, multi-method walkthroughs of harder SAT math problems — strong for quadratics and nonlinear function" },
  { name: "UWorld College Prep", url: "https://www.youtube.com/channel/UChqZQKIfrkOsHcqIg6BMv1Q", why: "Short, focused instructor-led lessons and strategy/shortcut videos built specifically for the post-2023 Digita" },
  { name: "The Organic Chemistry Tutor", url: "https://www.youtube.com/@TheOrganicChemistryTutor", why: "Not SAT-exclusive, but the clearest free source for the underlying math — triangles, circle formulas, arc leng" },
  { name: "LearnSATMath", url: "https://www.youtube.com/@learnsatmath", why: "Popular condensed SAT math topic reviews, good for a fast whole-domain refresher." },
];

/* key: "<domainId>|<skill>" → { query, picks: [{title, channel, url}] } */
const SKILL_VIDEOS = {
  // ---------- Reading & Writing · Information and Ideas ----------
  "info|Central Ideas": {
    query: "Digital SAT central ideas and details main idea question walkthrough example Reading and Writing",
    picks: [],
  },
  "info|Evidence & Support": {
    query: "Digital SAT command of quantitative evidence graph and table questions strategy walkthrough",
    picks: [],
  },
  "info|Inferences": {
    query: "Digital SAT inferences question strategy \"most logically completes the text\" walkthrough",
    picks: [],
  },
  // ---------- Reading & Writing · Craft and Structure ----------
  "craft|Words in Context": {
    query: "\"Words in Context\" digital SAT question walkthrough youtube video Reading and Writing",
    picks: [
      { title: "Words in Context (Vocab) Questions on the Digital SAT: Strategies & Practice", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=dFQaoOGYhTk" },
      { title: "How to Tackle Words in Context (Vocab) Questions on the Digital SAT", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=C3F1Nwdlwv0" },
    ],
  },
  "craft|Text Structure & Purpose": {
    query: "\"Text Structure and Purpose\" digital SAT OR DSAT question walkthrough youtube video",
    picks: [
      { title: "How to Solve DSAT Text Structure and Purpose Questions", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=U3qWNZgoejU" },
      { title: "Khan Academy \"Text Structure & Purpose\" Questions", channel: "Not identified in search results (walkthrough of K", url: "https://www.youtube.com/watch?v=1Iz8AbdIPgc" },
    ],
  },
  "craft|Cross-Text Connections": {
    query: "\"Cross-Text Connections\" digital SAT question walkthrough youtube video Reading and Writing",
    picks: [
      { title: "Digital SAT: Cross-Text Connections (FULL GUIDE)", channel: "SAT Mastermind", url: "https://www.youtube.com/watch?v=yfn_VRLG5rg" },
      { title: "How to Approach Cross-Text Connections Questions on the Digital SAT", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=EyqHcKfzBxo" },
    ],
  },
  // ---------- Reading & Writing · Expression of Ideas ----------
  "expr|Transitions": {
    query: "\"SAT transitions\" question type strategy walkthrough site:youtube.com/watch 2025",
    picks: [
      { title: "Transitions Questions on the Digital SAT: Strategies & Practice", channel: "Ivy League Mentors", url: "https://www.youtube.com/watch?v=kz_P_b3H0oA" },
    ],
  },
  "expr|Rhetorical Synthesis": {
    query: "\"rhetorical synthesis\" digital SAT \"student wants to\" bullet points strategy site:youtube.com/watch",
    picks: [
      { title: "Rhetorical Synthesis Questions on the Digital SAT: Strategies & Practice", channel: "Ivy League Mentors", url: "https://www.youtube.com/watch?v=lo7LFbac_9o" },
    ],
  },
  // ---------- Reading & Writing · Standard English Conventions ----------
  "conv|Punctuation & Boundaries": {
    query: "\"Digital SAT\" boundaries punctuation rules explained semicolon colon dash video",
    picks: [
      { title: "All SAT Punctuation Rules in 15 Minutes", channel: "Channel name not shown in search results (verify o", url: "https://www.youtube.com/watch?v=WCHyeJKWD84" },
      { title: "Digital SAT Standard English Conventions: Boundaries", channel: "Channel name not shown in search results (verify o", url: "https://www.youtube.com/watch?v=M4EOqgOC4ks" },
    ],
  },
  "conv|Subject-Verb Agreement": {
    query: "\"Digital SAT\" subject verb agreement lesson prepositional phrase trap youtube",
    picks: [
      { title: "SAT Grammar: Subject-Verb Agreement MADE EASY", channel: "Channel name not shown in search results (verify o", url: "https://www.youtube.com/watch?v=8ARYtkPHfds" },
      { title: "Digital SAT 2024: Mastering Subject Verb Agreement", channel: "Channel name not shown in search results (verify o", url: "https://www.youtube.com/watch?v=62eknLeV84s" },
    ],
  },
  "conv|Verb Forms & Pronouns": {
    query: "\"Digital SAT\" \"form structure and sense\" verb tense finite non-finite pronoun antecedent lesson",
    picks: [
      { title: "How to Solve DSAT Form Structure and Sense - Finite or Non-Finite Verbs", channel: "Channel name not shown in search results (verify o", url: "https://www.youtube.com/watch?v=uO4A797fj5o" },
      { title: "CHALLENGE: Subject/Pronoun Questions on the SAT (DIGITAL SAT PRACTICE)", channel: "Channel name not shown in search results (verify o", url: "https://www.youtube.com/watch?v=STJpR22CtpE" },
    ],
  },
  // ---------- Math · Algebra ----------
  "alg|Linear Equations": {
    query: "\"Digital SAT\" math \"linear equations in one variable\" question walkthrough youtube.com/watch 2025",
    picks: [
      { title: "SAT Math on Khan Academy: Solving Linear Equations and Inequalities (Foundations)", channel: "Khan Academy SAT", url: "https://www.youtube.com/watch?v=vrPbC9fao6Y" },
      { title: "Digital SAT Algebra Linear Equations | Hard Part 1", channel: "Not named in the search result (Digital SAT Algebr", url: "https://www.youtube.com/watch?v=h_SIXRLwUWc" },
    ],
  },
  "alg|Systems of Equations": {
    query: "\"Digital SAT\" math \"systems of two linear equations in two variables\" Desmos walkthrough youtube.com/watch",
    picks: [
      { title: "SAT Math: Systems of two linear equations in two variables - August SAT Prep", channel: "Not named in the search result", url: "https://www.youtube.com/watch?v=oc94QDQCnJs" },
      { title: "Systems of Linear Equations on the SAT — Fast & Easy Desmos Calculator Tricks, 2 examples ", channel: "Not named in the search result", url: "https://www.youtube.com/watch?v=3fOwcTwxeFQ" },
    ],
  },
  "alg|Linear Functions & Graphs": {
    query: "\"Digital SAT\" math \"linear functions\" slope-intercept from a table or graph Desmos youtube.com/watch 2025",
    picks: [
      { title: "SAT Math on Khan Academy: Graphs of Linear Equations and Functions (Foundations)", channel: "Khan Academy SAT", url: "https://www.youtube.com/watch?v=yIA8hlzqBJ8" },
      { title: "Digital SAT Math - Solving Problem on Linear Functions in Slope-Intercept Form Using Desmo", channel: "Not named in the search result", url: "https://www.youtube.com/watch?v=SRxukm38PIo" },
    ],
  },
  // ---------- Math · Advanced Math ----------
  "adv|Quadratics": {
    query: "\"digital SAT\" quadratics video tutorial vertex form factored form Desmos youtube.com/watch",
    picks: [
      { title: "Conquer SAT Quadratics: Everything You NEED to Know for SAT Digital Math (No Fluff, Just R", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=ZfpABadeiUc" },
      { title: "Digital SAT Math (Quadratics)", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=0RvtZ63PhQM" },
    ],
  },
  "adv|Exponents & Radicals": {
    query: "\"digital SAT\" math exponents radicals rational exponents lesson youtube.com/watch",
    picks: [
      { title: "Exponents & Radicals for the Digital SAT", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=q9U4-XvXxhM" },
      { title: "Exponents and Radicals | Advanced Math | Digital SAT Math | MathPrep with Ahmad Bilal", channel: "MathPrep with Ahmad Bilal", url: "https://www.youtube.com/watch?v=KpxLpYgK6pc" },
    ],
  },
  "adv|Nonlinear Functions": {
    query: "\"digital SAT\" advanced math nonlinear functions exponential polynomial graphs walkthrough youtube.com/watch",
    picks: [
      { title: "SAT Math on Khan Academy: Nonlinear Functions (Foundations)", channel: "Khan Academy SAT", url: "https://www.youtube.com/watch?v=ZLp-3Z8jouo" },
      { title: "SAT Math on Khan Academy: Polynomial and Other Nonlinear Graphs (Foundations)", channel: "Khan Academy SAT", url: "https://www.youtube.com/watch?v=Kr7ns3CZ6o0" },
    ],
  },
  // ---------- Math · Problem-Solving & Data Analysis ----------
  "data|Ratios & Percentages": {
    query: "\"Ratios, Rates, Proportional Relationships, and Units\" digital SAT math lesson youtube.com/watch",
    picks: [
      { title: "Overcoming Digital SAT Math - Ratios and Proportions", channel: "Not identified in search results (part of the \"Ove", url: "https://www.youtube.com/watch?v=mH-cHRpK5Gg" },
      { title: "SAT Math on Khan Academy: Ratios, Rates, and Proportions (Foundations)", channel: "Not identified in search results (walkthrough of K", url: "https://www.youtube.com/watch?v=HFticqOjvH4" },
    ],
  },
  "data|Statistics & Probability": {
    query: "\"SAT MATH\" \"One-Variable Data\" OR \"Probability and Conditional Probability\" digital SAT lesson youtube.com/watch",
    picks: [
      { title: "SAT MATH: One-Variable Data: Distributions and Measures of Center and Spread • AceIt", channel: "AceIt", url: "https://www.youtube.com/watch?v=pLGI-On2pek" },
      { title: "SAT Math on Khan Academy: Center, Spread, and Shape of Distributions", channel: "Not identified in search results (walkthrough of K", url: "https://www.youtube.com/watch?v=HtkQbzDXKDA" },
    ],
  },
  "data|Data Interpretation": {
    query: "\"Two-Variable Data: Models and Scatterplots\" digital SAT math video youtube.com/watch",
    picks: [
      { title: "SAT Math: Scatterplots", channel: "Not identified in search results", url: "https://www.youtube.com/watch?v=K3IXKk2Zkuo" },
      { title: "SAT MATH: Two-Variable Data: Models & Scatterplots • AceIt", channel: "AceIt", url: "https://www.youtube.com/watch?v=mVEgpc2UHvQ" },
    ],
  },
  // ---------- Math · Geometry & Trigonometry ----------
  "geo|Angles & Triangles": {
    query: "\"Digital SAT\" math similar triangles congruent special right triangles 30-60-90 45-45-90 lesson site:youtube.com/watch",
    picks: [
      { title: "Triangles | Special Triangles | Congruent & Similar Triangles | Digital SAT", channel: "Math with Ahmad Bilal", url: "https://www.youtube.com/watch?v=qv98F3DirOo" },
      { title: "Similar Triangles and Similar Figures for the Digital SAT | Math Jamboree 15003001", channel: "Math Jamboree", url: "https://www.youtube.com/watch?v=UU9CD38VhTY" },
    ],
  },
  "geo|Circles & Area": {
    query: "\"Digital SAT\" math circles arc length sector area equation of a circle radians lesson 2024 OR 2025 youtube.com/watch",
    picks: [],
  },
  "geo|Right-Triangle Trig": {
    query: "\"Digital SAT\" math right triangle trigonometry SOHCAHTOA \"complementary angles\" sin cos walkthrough youtube.com/watch",
    picks: [
      { title: "Trigonometry (SAT Math Geometry Lesson)", channel: "Channel not identified in search results", url: "https://www.youtube.com/watch?v=l8bVS3hDHxs" },
      { title: "SOHCAHTOA? No Problem! Right Triangle Trig for the SAT", channel: "Channel not identified in search results", url: "https://www.youtube.com/watch?v=Ycy9rLuR-SI" },
    ],
  },
};

/* Broader topics that aren't a single skill */
const TOPIC_VIDEOS = {
  desmos: { label: "Using the built-in Desmos calculator", query: "Digital SAT Desmos calculator tips and tricks" },
  pacing: { label: "Pacing and timing strategy", query: "Digital SAT pacing strategy timing tips" },
  adaptive: { label: "How the adaptive test works", query: "Digital SAT adaptive modules how scoring works explained" },
  spr: { label: "Fill-in (student-produced response) answers", query: "Digital SAT student produced response grid in rules" },
  overview: { label: "Full Digital SAT overview", query: "Digital SAT format overview what to expect" },
};

function videosForSkill(domainId, skill) {
  const entry = SKILL_VIDEOS[domainId + "|" + skill];
  if (!entry) return null;
  return { query: entry.query, url: ytSearchUrl(entry.query), picks: entry.picks || [] };
}
function videosForDomain(domainId) {
  const dom = typeof DOMAIN_BY_ID !== "undefined" ? DOMAIN_BY_ID[domainId] : null;
  if (!dom) return [];
  return dom.skills.map(s => ({ skill: s, ...videosForSkill(domainId, s) })).filter(v => v.query);
}
